### List all messages

Get http://localhost:3000/messages

###Create a new message

POST http://localhost:3000/messages
Content-Type: application/json

{
    "content": "hi there"
}

### List one messages by id

Get http://localhost:3000/messages/7436